import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useState, useEffect} from 'react';

export default function Home() {
  const [selectedCategories, setSelectedCategories] = useState({movies: false, 
    shows: false, 
    songs: false, 
    artists: false, 
    books: false});
  const [nextButton, setNextButton] = useState(false);

   useEffect(() => {
      const categories = Object.values(selectedCategories);
      if(categories.includes(true)){
        setNextButton(true);
      }
      else {
        setNextButton(false);
      }

   }, [selectedCategories])

  function handleCategoryClick(e: React.MouseEvent<HTMLElement>):void{
    e.preventDefault();
    const target = e.target as HTMLInputElement;
    console.log(target.id)

    
    
    
    if (target.id === 'artists'){
      const selected = selectedCategories.artists
      setSelectedCategories({...selectedCategories, artists: !selected})
      
    }
    if (target.id === 'songs'){
      const selected = selectedCategories.songs
      setSelectedCategories({...selectedCategories, songs: !selected})
    }
    if (target.id === 'movies'){
      const selected = selectedCategories.movies
      setSelectedCategories({...selectedCategories, movies: !selected})
    }
    if (target.id === 'books'){
      const selected = selectedCategories.books
      console.log('selected: ', selected)
      const newCategories = {...selectedCategories, books: !selected}
      setSelectedCategories({...newCategories})
    }
    if (target.id === 'shows'){
      const selected = selectedCategories.shows
      console.log('selected: ', selected)
      const newCategories = {...selectedCategories, shows: !selected}
      setSelectedCategories({...newCategories})
    }
   
    console.log(selectedCategories)
  }

  
  
  return (
    <div className={styles.container}>
      <Head>
        <title>MyTop5</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.login}>
        <p>Already have a top 5? <a href="/login"><span id="loginLink">Login</span></a></p>
        
      </div>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to MyTop5!
        </h1>

        <p className={styles.description}>
          Select from the categories below to generate your top 5
        </p>
        <div className={styles.categoryGrid}>
          <button id="movies" className={!selectedCategories.movies ? `${styles.movies}` : `${styles.moviesSelected}`} onClick={handleCategoryClick}>
            Movies
          </button>
          <button id="shows" className={!selectedCategories.shows ? `${styles.shows}` : `${styles.showsSelected}`} onClick={handleCategoryClick}>
            Shows
          </button>
          <button id="songs" className={!selectedCategories.songs ? `${styles.songs}` : `${styles.songsSelected}`} onClick={handleCategoryClick}>
            Songs
          </button>
          <button id="artists" className={!selectedCategories.artists ? `${styles.artists}` : `${styles.artistsSelected}`} onClick={handleCategoryClick}>
            Artists
          </button>
          <button id="books" className={!selectedCategories.books ? `${styles.books}` : `${styles.booksSelected}`} onClick={handleCategoryClick}>
            Books
          </button>
        </div>
      </main>
      <div className={styles.next}>
          {nextButton ? <button >Next</button> : null }
        </div>
      

      <footer className={styles.footer}>
        {/* <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a> */}
      </footer>
    </div>
  )
}
