import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useState, useEffect} from 'react';
import Selections from './components/Selections'
import MoviesSelect from './select/movies'
import Link from 'next/link'
import { useRouter } from 'next/router'

export default function Home() {
  const [selectedCategories, setSelectedCategories] = useState({movies: false, 
    shows: false, 
    songs: false, 
    artists: false, 
    books: false});
  const [nextButton, setNextButton] = useState<boolean>(false);
  const router = useRouter();
  

   useEffect(() => {
      const categories = Object.values(selectedCategories);
      if(categories.includes(true)){
        setNextButton(true);
      }
      else {
        setNextButton(false);
      }

   }, [selectedCategories])

  const handleCategoryClick = (e: React.MouseEvent<HTMLElement>):void => {
    e.preventDefault();
    const target = e.target as HTMLInputElement;
    console.log(target.id)
 
    
    if (target.id === 'artists'){
      const selected = selectedCategories.artists
      setSelectedCategories({...selectedCategories, artists: !selected})
      
    }
    if (target.id === 'songs'){
      const selected = selectedCategories.songs
      setSelectedCategories({...selectedCategories, songs: !selected})
    }
    if (target.id === 'movies'){
      const selected = selectedCategories.movies
      setSelectedCategories({...selectedCategories, movies: !selected})
    }
    if (target.id === 'books'){
      const selected = selectedCategories.books
      const newCategories = {...selectedCategories, books: !selected}
      setSelectedCategories({...newCategories})
    }
    if (target.id === 'shows'){
      const selected = selectedCategories.shows
      const newCategories = {...selectedCategories, shows: !selected}
      setSelectedCategories({...newCategories})
    }
   
  }

  const handleNextClick = () => {
    console.log(selectedCategories)
    const filteredCategories = Object.keys(selectedCategories).filter(category => selectedCategories[category as keyof typeof selectedCategories] === true)
    console.log('filtered categories: ', filteredCategories)
    
    router.push({pathname: `/select/[location]`, query : { location: filteredCategories[0] }})
    window.localStorage.setItem('categories', JSON.stringify(filteredCategories));
    
  }

  
  return (
    <div className={styles.container}>
      <Head>
        <title>MyTop5</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className={styles.login}>
          <p>Already have a top 5? <a href="/login"><span id="loginLink">Login</span></a></p>
        </div>
      </header>
      <Selections selectedCategories={selectedCategories} handleCategoryClick={handleCategoryClick}/>
      <div className={styles.next}>
          {nextButton ? 
              <button onClick={handleNextClick}>Next</button> 
            : null }
        </div>
      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
